set LD_LIBRARY_PATH=

call "%ENV_LOADER%"



set MPICOMMAND=mpiexec -n %NP% %MACHINEFILE% %MPI_ACCESSORY_OPTIONS% -genvlist HOME,PATH,USERNAME,WM_PROJECT_DIR,WM_PROJECT_INST_DIR,WM_OPTIONS,FOAM_LIBBIN,FOAM_APPBIN,FOAM_USER_APPBIN,FOAM_CONFIG,MPI_BUFFER_SIZE

