unset LD_LIBRARY_PATH

. "$ENV_LOADER"

set -e
set -o pipefail


# export MACHINEFILE="-machinefile $HOSTFILE"
# echo MACHINEFILE: $MACHINEFILE

export PYTHON_COMMAND="python"

export MPICOMMAND="mpirun --oversubscribe -np $NP $MACHINEFILE \
--prefix $MPI_ARCH_PATH -x PATH -x LD_LIBRARY_PATH -x OPAL_PREFIX -x MPI_ARCH_PATH -x HELYX_PROJECT_DIR -x HELYX_OPTIONS -x HELYX_CONFIG"

